version : 0.1

phases:
  build:
    commands:
      - echo Enter the build phase...
      - mvn clean package
    post_build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    - target/test.jar
  discard-paths: yes 